void menu(int i);
void criaarq(int n);
void printEntrada(int n);
int *getEntrada(int n);
void menuBubble(int n);
float bubblesort(int n);
void wreadSort(int n,int *v,int op);
void readSort(int n,int op);
void menuSelection(int n);
float selectionsort(int n);
void menuInsertion(int n);
float insertionsort(int n);
